project:
  type: website
  output-dir: docs

website:
  title: "Justin Klip's Website"
  navbar:
    left:
      - href: justin_site.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



